CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    login TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
    number_hash BYTEA PRIMARY KEY,
    number TEXT NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id)
);
